POST http://localhost:8080/users/login?username=toja8
Content-Type: application/json

{
  "username": "toja8",
  "password": "toja8"
}

###

POST http://localhost:8080/comment/create
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJodHRwOi8vbG9jYWxob3N0OjgwODAiLCJleHAiOjE3NDMwMjI2OTcsInN1YiI6InRvamE3In0.peM5YKNm7K2CJOSH4o6MdH71AS0SoiOeJkVLPrAZtM8
Content-Type: application/json

{
  "content": "Something",
  "postId": 2
}

###
POST http://localhost:8080/users/login?username=toja6
Content-Type: application/json

{
  "username": "toja6",
  "password": "toja6"
}

###
POST http://localhost:8080/users/login
Content-Type: application/json

{
  "username": "toja8",
  "password": "toja8"
}

###
DELETE http://localhost:8080/comment/delete/creator
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJodHRwOi8vbG9jYWxob3N0OjgwODAiLCJleHAiOjE3NDMwMjMwMjksInN1YiI6InRvamE4In0.LkW0Dvu2KD5vltoaIKTI_oIa9-V44dmsVK-G-UoEG9E
Content-Type: application/json

{
  "id": 2,
  "content": "What",
  "accountId": 15,
  "postId": 2
}

###
DELETE http://localhost:8080/comment/delete/post-creator
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJodHRwOi8vbG9jYWxob3N0OjgwODAiLCJleHAiOjE3NDMwMjMzNzAsInN1YiI6InRvamE4In0.a-BADBltyY-JMck64PIjQHv2sJ-syEXc5JOj8EOPmTI
Content-Type: application/json

{
  "id": 2,
  "content": "What",
  "accountId": 15,
  "postId": 2
}