POST http://localhost:8080/users/login?username=toja8
Content-Type: application/json

{
  "username": "toja8",
  "password": "toja8"
}

###

POST http://localhost:8080/post/create
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJodHRwOi8vbG9jYWxob3N0OjgwODAiLCJleHAiOjE3NDMwMTc3NjksInN1YiI6InRvamE4In0.YeVLr47a9MdcI20AOvbDMbfDF4T8i96MvJTaa131lok
Content-Type: application/json

{
  "content": "unique"
}

###

DELETE http://localhost:8080/post/delete
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJodHRwOi8vbG9jYWxob3N0OjgwODAiLCJleHAiOjE3NDMwMTgzNzMsInN1YiI6InRvamE4In0.RG-H2tF4XcmMSb4-gObQ_T9aWBmRhgwMMPojawen7F8
Content-Type: application/json

{
  "id": 10,
  "content": "unique",
  "accountId": 16
}

###
POST http://localhost:8080/users/login?username=toja7
Content-Type: application/json

{
  "username": "toja7",
  "password": "toja7"
}