POST http://localhost:8080/comment/create?postId=2
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJodHRwOi8vbG9jYWxob3N0OjgwODAiLCJleHAiOjE3NDI5MzgyNzYsInN1YiI6InRvamE4In0.qlfbz4iqNakQhYJdkxjmEocSN09wYHbnyWWTh1m9UF8
Content-Type: application/json

{
  "content": "What"
}

###
GET http://localhost:8080/post?page=1&size=3&sortBy=id&ascending=true
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJodHRwOi8vbG9jYWxob3N0OjgwODAiLCJleHAiOjE3NDI5MzczOTEsInN1YiI6InRvamE4In0.PT_mZGyU6ZWijNhqCEn5eYA9A_5RNysOtkOkN-ZYHYM
Accept: application/json

###
GET http://localhost:8080/post
Content-Type: application/json

{}

###
POST http://localhost:8080/users/register
Content-Type: application/json

{
  "password": "toja8",
  "username": "toja8"
}

###
GET http://localhost:8080/trigger
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJodHRwOi8vbG9jYWxob3N0OjgwODAiLCJleHAiOjE3NDI5NTAyODgsInN1YiI6InRvamE4In0._twDtdUPk5UNd9JzyoL8bXvGfUZ6s14oDtlzZc9M6UU
Accept: application/json

###
GET http://localhost:8080/users
Authorization: Basic Karolina Karo
Accept: application/json

###JSESSIONID=6DFBE807949DEBA141FEA1684938DD95
POST http://localhost:8080/users/login?username=toja8
Content-Type: application/json

{
  "password": "toja8",
  "username": "toja8"
}

###

POST http://localhost:8080/post/create
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJodHRwOi8vbG9jYWxob3N0OjgwODAiLCJleHAiOjE3NDI4OTc4OTQsInN1YiI6InRvamE4In0.r7qovd-71ZnplD6KGBS-S6QFzSyHN9Q7DeB9t8bkqaM
Content-Type: application/json

{
  "content": "Post 6"
}


